import { montserrat, poppins } from "./fonts";
import "./globals.css";
import "@total-typescript/ts-reset";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.className} ${poppins.className}`}>
      <body>{children}</body>
    </html>
  );
}
